Add vector implementation
salavay/first-term pull request #1
Opened 2020-06-30 17:51 UTC by salavay

2020-07-01 11:59 UTC, kt-cpp commented on vector/vector.h
> +        newData[i] = other[i];
Давай сразу конструктор копирования тут вызовем

2020-07-01 12:00 UTC, kt-cpp commented on vector/vector.h
> +  }// O(N) strong
Эти комменты в конце реализаций выглядят ужасно, перенеси ближе к сигнатуре функции

2020-07-01 12:00 UTC, kt-cpp commented on vector/vector.h
> +    T *newData = nullptr;
Почему здесь ```camelCase``` ?

2020-07-01 12:02 UTC, kt-cpp commented on vector/vector.h
> +      push_back_realloc(valSaved);
Лишнее копирование при отстутствиии реалокации

2020-07-01 12:04 UTC, kt-cpp commented on vector/vector.h
> +      reserve(capacity_ == 0 ? 1 : capacity_ * 2);
Копипаста из `calc_capactiy`

2020-07-01 12:05 UTC, kt-cpp commented on vector/vector.h
> +    }
Деструкторы не в порядке конструирования (т.е. скорее всего порядок был обратным)

2020-07-01 12:07 UTC, kt-cpp commented on vector/vector.h
> +      }
А как это работает вообще? Ты ведь вызовешь деструктор у ```end()```

2020-07-01 12:09 UTC, kt-cpp commented on vector/vector.h
> +      for (i++; i < new_size; i++) {
Ужасно

2020-07-01 12:10 UTC, kt-cpp requested changes
Переписать все циклы на нормальные (человеческие), избавиться от копипасты, потом еще раз глянем

2020-07-01 13:04 UTC, salavay commented on vector/vector.h
> +        newData[i] = other[i];
> Переписать все циклы на нормальные (человеческие), избавиться от копипасты, потом еще раз глянем

Все замечания исправлены

2020-07-01 13:05 UTC, salavay commented
> Переписать все циклы на нормальные (человеческие), избавиться от копипасты, потом еще раз глянем

Все замечания исправлены

2020-07-01 14:27 UTC, kt-cpp commented on vector/vector.h
> +    }
Давай через `while + pop_back`

И `if` не нужен

2020-07-01 14:28 UTC, kt-cpp commented on vector/vector.h
> +  }
Можно это вызывать в деструкторе

2020-07-01 14:29 UTC, kt-cpp commented on vector/vector.h
> +    new(data_ + size_)  T(data_[size_ - 1]);
Ссылка на элемент становится невалидной, если реалокация

2020-07-01 14:29 UTC, kt-cpp commented on vector/vector.h
> +    for (size_t i = size_; i-- > size_ - delta;) {
Можно,пожалуйста, снова переписать этот цикл

2020-07-01 14:30 UTC, kt-cpp commented on vector/vector.h
> +    size_ -= delta;
Кстати лучше `size_` уменьшать в цикле повыше

2020-07-01 14:32 UTC, kt-cpp commented on vector/vector.h
> +  }
А чего бы не через `reserve`?

2020-07-01 14:34 UTC, kt-cpp requested changes
Еще чуть-чуть

2020-07-01 15:39 UTC, salavay commented on vector/vector.h
> +  }
Потому что при reserve происходит копирование, а я хочу сначала положить новый элемент в новую память, а потом уже скопировать элементы из ```data_```, чтобы при исключении сохранялись строгие гарантии

2020-07-01 15:47 UTC, salavay commented on vector/vector.h
> +    for (size_t i = size_; i-- > size_ - delta;) {
fixed

2020-07-01 15:47 UTC, salavay commented on vector/vector.h
> +    size_ -= delta;
fixed

2020-07-01 15:47 UTC, salavay commented on vector/vector.h
> +  }
Потому что при reserve происходит копирование, а я хочу сначала положить новый элемент в новую память, а потом уже скопировать элементы из ```data_```, чтобы при исключении сохранялись строгие гарантии

2020-07-01 15:47 UTC, salavay commented on vector/vector.h
> +    new(data_ + size_)  T(data_[size_ - 1]);
Не очень понял, что становится невалидным. Переписал через push_back

2020-07-01 15:47 UTC, salavay commented on vector/vector.h
> +  }
fixed

2020-07-01 15:47 UTC, salavay commented on vector/vector.h
> +    }
fixed

2020-07-01 16:20 UTC, kt-cpp commented on vector/vector.h
> +  }
Я имел ввиду, почему не сделать вот так:
```
vector tmp;
tmp.reserve(calc_new_capactiy());
for (...) { push_back }
push_back(new_elem)
swap
```
Возможно, я в чем-то неправ, давай обсудим

2020-07-01 16:24 UTC, kt-cpp commented on vector/vector.h
> +  }
Тем не менее, `reserve` уже делает `swap-trick`, не понимаю зачем тебе сначала класть новый элемент, а потом все остальные в новую `_data`

2020-07-01 16:26 UTC, kt-cpp commented on vector/vector.h
> +  }
А этот метод уже нигде не используется ...

2020-07-01 16:27 UTC, kt-cpp requested changes
Пара вопросов

2020-07-03 15:17 UTC, salavay commented on vector/vector.h
> +  }
fixed

2020-07-03 15:20 UTC, salavay commented on vector/vector.h
> +  }
Просто хотелось сделать так, чтобы сначала первый добавлять. Строго не скажу, почему. Думалось, что вероятней всего он может выкинуть ошибку, тогда мы не будем копировать ```data_```. Переписал на ```reserve```. Так действительно гораздо читабельней.

2020-07-03 18:14 UTC, kt-cpp approved these changes
Норм

2020-07-03 18:14 UTC, merged