Added bigint-opt HW
salavay/first-term pull request #4
Opened 2020-07-08 23:58 UTC by salavay

Cleaned code in bigint (refactored default constructor, loops now don't use forEach, comparing uses compare_abs())

2020-07-09 09:18 UTC, kt-cpp requested changes
В целом неплохо. Но ты сам усложнил себе жизнь работая с произвольным `T`

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/shared.h
> +    data_ = other.data_;
[minor] Инициализация членов класса

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +      }
[minor] Если тут вылетит исключение в конструкторе, то ресурсы префикса созданных элементов утекут

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +        swap(dynamic_data_, tmp.dynamic_data_);
[minor] Лучше не использовать тернарник, если он ничего не возвращает, а заменить на обычный `if`

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +        swap_data(tmp, *this);
[minor] Аналогично про тернарник

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +        size_++;
[minor] Чтобы иметь строгую гарантию размер нужно увеличивать после конструирования

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +        }
[minor]  Тут будут проблемы в случае исключения в конструкторе

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +  void resize(size_t const &n, T const &val) {
Почему resize выше перевызывает этот, а тело этого содержит почти полностью его тело?

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +  void resize(size_t const &n, T const &val) {
Или вообще `T const &val = T()`, константная ссылка продлевает жизнь временным объектам

2020-07-09 09:18 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +    }
[minor] Снова проблема с искдючениями в конструкторе

2020-07-09 11:52 UTC, salavay commented on bigint-optimized/shared.h
> +    data_ = other.data_;
fixed

2020-07-09 11:52 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +      }
fixed

2020-07-09 11:52 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +        swap(dynamic_data_, tmp.dynamic_data_);
fixed

2020-07-09 11:53 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +        swap_data(tmp, *this);
fixed

2020-07-09 11:53 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +        size_++;
fixed

2020-07-09 11:53 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +        }
fixed

2020-07-09 11:54 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +  void resize(size_t const &n, T const &val) {
С ссылкой поправил. Теперь весь код находиться в одном ```resize(n, val)```

2020-07-09 11:55 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +    }
fixed

2020-07-09 18:24 UTC, kt-cpp requested changes
Близко

2020-07-09 18:24 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +  void clear_static(T *to, size_t const &first, size_t const &last) {
[minor] Нет смысла принимать по ссылке, просто принимай по значению

2020-07-09 18:24 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +    }
[minor] Перепиши через понятный `for` с `[i - 1]` без этих приколов с условиями по `i--`, ибо сейчас например ты не удаляешь ячейку с индексом `first`, что не очевидно. Вообще хорошо в комментах описать констракт

2020-07-09 18:24 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +  void safe_initialize_with_static(T *to, size_t const &first, size_t const &last, T val) {
Зачем принимать по значению `val``?

2020-07-09 18:24 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +  void resize(size_t const &n, T val) {
[minor] И тут зачем по значению?

2020-07-09 18:24 UTC, kt-cpp commented on bigint-optimized/small_object_shared_vector.h
> +      clear_static(to, i, 0);
[minor] Зачем это всё, ели есть `clear_static`

2020-10-13 14:37 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +  void clear_static(T *to, size_t const &first, size_t const &last) {
fixed везде

2020-10-13 14:37 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +    }
fixed

2020-10-13 14:38 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +  void safe_initialize_with_static(T *to, size_t const &first, size_t const &last, T val) {
fixed теперь по ссылке

2020-10-13 14:38 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +  void resize(size_t const &n, T val) {
fixed, принимаю как в стандарте по конст ссылке, resize теперь один

2020-10-13 14:38 UTC, salavay commented on bigint-optimized/small_object_shared_vector.h
> +      clear_static(to, i, 0);
fixed

2020-10-13 15:01 UTC, kt-cpp approved these changes

2020-10-13 15:01 UTC, merged